# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
 
  config.vm.box = "puphpet/ubuntu1404-x32"

  config.vm.box = "puphpet/ubuntu1404-x32"

  config.vm.synced_folder "../../vagrant-share/", "/shared-host-folder"
  config.vm.synced_folder "../../../../", "/shared-host-folder-project-root"
  config.vm.synced_folder "../../../../../", "/shared-host-git-repo"

 
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y git nano make gcc p7zip-full openjdk-7-jdk maven mingw32
   
     
	mkdir -p /home/vagrant/.m2/
	chown -R vagrant /home/vagrant/.m2/
	cp -f /shared-host-folder/settings.xml /home/vagrant/.m2/settings.xml
	JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:bin/javac::")
	sed -i "s|JAVA_HOME32|$JAVA_HOME|g" /home/vagrant/.m2/settings.xml
	chown vagrant /home/vagrant/.m2/settings.xml
   
   SHELL
end
