name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        cache: maven
        
    - name: Build & Test with Maven
      run: mvn --batch-mode clean verify
      
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
        
    - name: Publish artifacts to GitHub Packages
      run: mvn --batch-mode deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  signal-vdm-vscode:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: ${{ github.repository }} == "overturetool/overture-fmu"
    
    steps:
      - name: Checking out
        uses: actions/checkout@v3
        
      - name: Getting POM artifact info
        id: get_artifact_info
        run: |
          echo "version=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "groupId=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.groupId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "artifactId=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
   
      - name: Send repository dispatch http request to VDM-VSCode
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.VDM_VSCODE_PAT }}
          repository: glennlaursen/vdm-vscode
          event-type: new-jar
          client-payload: '{ "configId": "fmu-import-export", "version": "${{ steps.get_artifact_info.outputs.version }}" }'
