name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode package -pl :fmu-import-export -am
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
    - name: Archive Jar artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Jars
        path: core/fmu-import-export/target/*.jar
